name: focusfeed
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Firebase dependencies
  firebase_core: ^4.6.0
  file_picker: ^10.3.10
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.0.3
  google_sign_in: ^7.2.0  # For Google authentication
  sign_in_with_apple: ^7.0.1  # For Apple authentication (iOS only)
  image_picker: ^1.2.1
  google_mlkit_text_recognition: ^0.15.1
  image_cropper: ^12.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - web/ff-logo-transparent.png
